name: Deploy Frontend (InfinityFree)

on:
  push:
    branches: ["main"]
    paths:
      - "wwwroot/**" # CHá»ˆ cháº¡y khi cÃ³ sá»­a Ä‘á»•i trong thÆ° má»¥c wwwroot

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸš€ Sync to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.IF_HOST }}
          username: ${{ secrets.IF_USER }}
          password: ${{ secrets.IF_PASS }}
          local-dir: ./wwwroot/ # Láº¥y file tá»« wwwroot
          server-dir: htdocs/ # ÄÆ°a vÃ o htdocs
          dangerous-clean-slate: false
